# Generated by Django 5.1 on 2024-08-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_post_delete_blogpost"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="BlogPost",
        ),
    ]
