# Generated by Django 5.1 on 2024-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_post_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Goodness", max_length=400),
            preserve_default=False,
        ),
    ]
